name: app
description: A new Flutter project.
publish_to: "none"

# bundle ID : com.blank.sns
version: 1.2.1+1

#最後のビルド番号はずっと増えていく
#初回リリース：version: 1.0.0+1
#バグ修正リリース：version: 1.0.1+2
#新機能追加リリース：version: 1.1.0+3
#メジャーアップデートリリース：version: 2.0.0+4

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  firebase_performance: ^0.10.0
  firebase_dynamic_links: ^6.0.0
  firebase_remote_config: ^5.0.0

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  #google_mobile_ads: ^2.3.0
  google_fonts: ^6.2.1
  focused_menu: ^1.0.5
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  #animated_text_kit: ^4.2.2
  #qr_flutter: ^4.0.0
  #qr_code_scanner: ^1.0.0
  #pretty_qr_code: ^3.0.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^18.0.1
  #wave: ^0.2.0
  #flutter_staggered_animations: ^1.0.0
  #animations: ^2.0.2
  #url_launcher: ^6.0.20
  #shared_preferences: ^2.0.13
  #change_app_package_name: ^1.0.0
  cached_network_image: ^3.3.1
  #like_button: ^2.0.4
  #modal_bottom_sheet: ^2.0.1
  #share: ^2.0.4
  #camera: ^0.10.5+5
  #path_provider: ^2.0.15
  path: ^1.8.3
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  #google_maps_flutter: ^2.1.8
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  #introduction_screen: ^3.1.4
  #numberpicker: ^2.1.1

  #flutter_datetime_picker_plus: ^2.0.1
  #restart_app: ^1.1.1+1
  #timezone: ^0.9.2
  #once: ^1.5.1
  #workmanager: ^0.5.1
  #crypto: ^3.0.2
  #flutter_staggered_grid_view: ^0.7.0
  #smooth_page_indicator: ^1.0.1
  #dio: ^5.1.1
  #video_player: ^2.6.1
  #chewie: ^1.4.0
  #flutter_speed_dial: ^7.0.0
  #socket_io_client: ^2.0.2
  vibration: ^3.1.3
  in_app_purchase: ^3.1.7
  uuid: ^3.0.7
  #flutter_stripe: ^9.2.1
  confetti: ^0.8.0
  photo_view: ^0.15.0
  #external_path: ^1.0.3
  font_awesome_flutter: ^10.5.0
  #flutter_chat_ui: ^1.6.6
  image_cropper: ^9.1.0
  appinio_swiper: ^2.1.1

  flutter_riverpod:
  riverpod_generator:
  riverpod_annotation:
  freezed_annotation:

  #banner_listtile: ^2.2.0
  #grouped_list: ^5.1.2
  #smart_select: ^4.3.2
  #material_floating_search_bar_2: ^0.5.0
  #flutter_markdown: ^0.6.12
  #markdown_editable_textinput: ^2.0.2
  #flutter_slidable: ^3.1.0
  #fake_cloud_firestore: ^2.4.1+1
  #pull_to_refresh: ^2.0.0
  #flutter_dotenv: ^5.1.0
  webview_flutter: ^4.8.0
  #animated_snack_bar: ^0.4.0
  #lottie: ^2.7.0
  #shake: ^2.2.0
  #cupertino_will_pop_scope: ^1.2.1
  expandable: ^5.0.1
  #loading_animation_widget: ^1.2.0+4
  #in_app_review: ^2.0.8
  #geoflutterfire: ^3.0.3
  #timeline_tile: ^2.0.0
  #simple_ripple_animation: ^0.0.8
  #analyzer: ^6.2.0
  blur: ^4.0.0
  #purchases_flutter: ^6.16.0
  screenshot: ^3.0.0
  #image_gallery_saver: ^2.0.3
  #go_router: ^13.1.0
  #image: ^4.1.6
  #giphy_get: ^3.5.4
  gap: ^3.0.1
  #in_app_purchase_android: any
  #in_app_purchase_storekit: any
  shimmer:
  flutter_animate: ^4.5.0
  #flutter_keyboard_visibility: ^6.0.0
  import_sorter: ^4.6.0
  flutter_image_compress: ^2.3.0
  device_info_plus: ^11.1.1
  #hive_generator: ^2.0.1
  package_info_plus: ^8.3.0 
  flutter_blurhash: ^0.9.1
  blurhash_dart: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  card_swiper: ^3.0.1

  image: any
  path_provider: any
  flutter_hooks: ^0.20.5
  loading_indicator: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  hooks_riverpod: ^2.5.1
  dotted_border: ^2.1.0
  camera: ^0.10.6
  camera_android_camerax: ^0.6.8+2
  pretty_qr_code: ^3.3.0
  flutter_callkit_incoming: ^2.0.4+2
  change_app_package_name: ^1.4.0
  url_launcher: ^6.3.0
  #social_share: ^2.3.1
  #share_plus: ^11.0.0
  google_mobile_ads: ^5.2.0
  app_tracking_transparency: ^2.0.6
  algolia: ^1.1.2
  http: ^0.13.6
  pull_to_refresh: ^2.0.0
  twitter_login: ^4.4.2

  intl: any
  shared_preferences: ^2.3.3
  rxdart: ^0.27.7
  flutter_3d_controller: ^2.0.3
  go_router: ^15.1.2

dependency_overrides:
  intl: ^0.17.0
  flutter_lints: ^3.0.1
  camera_android_camerax: ^0.6.7
  camera: ^0.11.0
  http: ^0.13.0
  image_cropper_platform_interface: ^6.1.0
     
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^1.0.0
  build_runner:
  hive_generator: ^2.0.1
  freezed:
  json_serializable: ^6.5.4
  cider: ^0.2.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/icon_ios.png"
  background_color_ios: "080808"
  adaptive_icon_foreground: "assets/images/icons/icon_android.png"
  adaptive_icon_background: "#080808"
  #adaptive_icon_background: "assets/images/icons/icon_android.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/images/icons/
    - assets/images/stickers/sunglass_babies/
    - assets/images/community/
    - assets/images/popup/
    - assets/data/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Black.ttf
          weight: 900

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
