// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:app/main.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = flavor == "dev"
      ? FirebaseOptions(
          apiKey: 'AIzaSyCZA_7jMPI5b9MHQM7-cdywMhiCnnVLMvk',
          appId: '1:889410445548:android:53d67e153fae0a460185c9',
          messagingSenderId: '889410445548',
          projectId: 'chat-sns-project',
          storageBucket: 'chat-sns-project.appspot.com',
        )
      : FirebaseOptions(
          apiKey: 'AIzaSyAijj6k2nDwKikzngVjLLbr-L1uL-ID4K4',
          appId: '1:822316855484:android:d6889d2c2075677ca6e0b9',
          messagingSenderId: '822316855484',
          projectId: 'blank-project-prod',
          storageBucket: 'blank-project-prod.firebasestorage.app',
        );

  static FirebaseOptions ios = flavor == "dev"
      ? FirebaseOptions(
          apiKey: 'AIzaSyC8aB27Wo9Lo6NKgV2ctOSIJVQTztqitiM',
          appId: '1:889410445548:ios:f41ea77af09d59ee0185c9',
          messagingSenderId: '889410445548',
          projectId: 'chat-sns-project',
          storageBucket: 'chat-sns-project.appspot.com',
          iosClientId:
              '889410445548-e12j86agor31tgb0n6o0hbpqb8g8ltg3.apps.googleusercontent.com',
          iosBundleId: 'com.blank.sns.dev',
        )
      : FirebaseOptions(
          apiKey: 'AIzaSyAJVVrkpGQqt6nAPVmocfa8Rdy4sH2G62Q',
          appId: '1:822316855484:ios:cb0e33798aa5e3bfa6e0b9',
          messagingSenderId: '822316855484',
          projectId: 'blank-project-prod',
          storageBucket: 'blank-project-prod.firebasestorage.app',
          iosClientId:
              '822316855484-3gcaup6u2k9b8jfljdn56rilbsgekm9i.apps.googleusercontent.com',
          iosBundleId: 'com.blank.sns',
        );
}
