-dontwarn com.google.devtools.build.android.desugar.runtime.ThrowableExtension
-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry