name: Auto Version Bump

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'pubspec.yaml'

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip version]')"

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Determine version bump type
      id: bump-type
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"[major]"* ]]; then
          echo "type=major" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.head_commit.message }}" == *"[minor]"* ]]; then
          echo "type=minor" >> $GITHUB_OUTPUT
        else
          echo "type=patch" >> $GITHUB_OUTPUT
        fi

    - name: Bump version
      run: |
        flutter pub run cider bump ${{ steps.bump-type.outputs.type }}
        flutter pub run cider release

    - name: Get new version
      id: version
      run: echo "version=$(flutter pub run cider version)" >> $GITHUB_OUTPUT

    - name: Commit version bump
      run: |
        git add pubspec.yaml CHANGELOG.md
        git commit -m "🔖 Bump version to ${{ steps.version.outputs.version }} [skip ci]" || exit 0
        git push origin main